dateModified: 1576168476
email:
  fromEmail: fake@fake-email-address.com
  fromName: 'Servd Demo'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  41f0085a-91c4-4de0-8a54-a5d6419bb7a8:
    name: Common
plugins:
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: '1.0'
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
sections:
  7b9fa0a4-623a-43e2-83a8-3d013cc6902e:
    name: Home
    handle: home
    type: single
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      4a08a421-ed5e-4eb5-8dbc-018aed34c7d3:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: singles/home
    entryTypes:
      eff33001-900c-4d66-8603-109687a40252:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
siteGroups:
  30f1acc4-b407-4444-8edc-278ba32bf7c9:
    name: 'Servd Demo'
sites:
  4a08a421-ed5e-4eb5-8dbc-018aed34c7d3:
    baseUrl: 'http://localhost'
    handle: default
    hasUrls: true
    language: en
    name: 'Servd Demo'
    primary: true
    siteGroup: 30f1acc4-b407-4444-8edc-278ba32bf7c9
    sortOrder: 1
system:
  edition: solo
  name: 'Servd Demo'
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  2f7839c9-4c87-4bf6-9d3c-2181918ec980:
    name: 'Servd Assets'
    handle: servdAssets
    type: servd\AssetStorage\Volume
    hasUrls: true
    url: 'https://cdn.assets-servd.host/'
    settings:
      subfolder: ''
      projectSlug: ''
      securityKey: ''
      makeUploadsPublic: '1'
    sortOrder: 1
