dateModified: 1612526594
email:
  fromEmail: fake@fake-email-address.com
  fromName: 'Servd Demo'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 2.0.5
    settings:
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      injectCors: false
      projectSlug: ''
      securityKey: ''
system:
  edition: solo
  live: true
  name: 'Servd Demo'
  schemaVersion: 3.6.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
